### ISSUE TITLE
Redux bindActionCreators

### ISSUE THREAD

**Issue by olegmdev** [EvgenBabenko/incode-app#7]
https://github.com/EvgenBabenko/incode-app/blob/0fcc475220f6e372ec71264d6feff49fe6182a57/src/containers/Auth.jsx#L30

Consider using redux bindActionCreators https://redux.js.org/api-reference/bindactioncreators

**Comment by EvgenBabenko** [comment]
got it, to do
in new branch (f/async) i'm working on it

**Comment by EvgenBabenko** [comment]
fixed
